@host = localhost:3000
@access_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjM4MDkwNWY0YzQyNDRkM2U0M2E4NDAxIiwiZXhwIjoxNjY5NDU4NTAzfQ.2UVeB6C8lT_f4EySMzppmsyeODJiXPoagnvVUgR3URE

### 
GET http://{{host}}/
Content-Type: application/json
Authorization: {{access_token}}

{
}
### 

### 
GET http://{{host}}/health
Content-Type: application/json
Authorization: {{access_token}}

{
}
### 

### 
GET http://{{host}}/init
Content-Type: application/json

{
}
### 