@host = localhost:3000
@access_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjM4MDkwNWY0YzQyNDRkM2U0M2E4NDAxIiwiZXhwIjoxNjY5NTU1Mzk5fQ.1K-yQO4gG08NTLUawkwaTa2BdEjRmbDTrHuQVzlCJ6E
@access_token2 = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjM4MWQ4ZWZlY2FlMGY4Y2JlN2I1YzQ2IiwiZXhwIjoxNjY5NTQwNDgxfQ.64awt3gCi5cFh3A2pMbHd5Ivj8UtV8vhzIuz6phja7Q

### 
POST http://{{host}}/room
Content-Type: application/json
Authorization: {{access_token}}

{
    "title": "test", 
    "is_private": true
}
### 

### 
POST http://{{host}}/room/enter
Content-Type: application/json
Authorization: {{access_token2}}

{
    "room_number": "0002"
}
### 

### 
PUT http://{{host}}/room/start
Content-Type: application/json
Authorization: {{access_token}}

{
    "room_number": "0002"
}
### 